### ISSUE TITLE
Build fails on arm64

### ISSUE THREAD

**Issue by garbear** [kodi-game/game.libretro.scummvm#13]
Build command is missing from CMakeLists.txt:

```
CMake Error at CMakeLists.txt:37 (message):
  scummvm needs Android arm64-v8a build command in CMakeLists.txt!
```

**Comment by tpreclik** [comment]
I cannot confirm this. For me it compiles cleanly and works on arm64. Can we reenable arm64 as an officially supported platform of the kodi addon?

**Comment by tpreclik** [comment]
Ok I was wrong. The system I am on (osmc/vero4k+) is actually hybrid and compiles 32-bit ARM by default. Sorry about that. But also 32-bit arm is missing from the supported platforms...

**Comment by garbear** [comment]
Scummvm has been rebased on master. arm64 compiles.
