### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by CvH** [kodi-game/game.libretro.scummvm#20]
https://github.com/kodi-game/game.libretro.scummvm/commit/45e82cc1ca26684c40ff5a86d6a0c7944791cb9c#diff-7434c3013bedee2f409ff60bdbb26a2dL4
changed the version from `version="2.0.0.1"` -> `version="0.0.1.2"`

is this intended ?
old `game.libretro.scummvm-2.0.0.1.zip`
new `game.libretro.scummvm-0.0.1.2.zip`
this breaks kodis addon updates

**Comment by garbear** [comment]
@fetzerch looks like the core failed to build and a default template commit was pushed

**Comment by fetzerch** [comment]
The core built fine, but it has an undefined symbol and the script refuses to load it. I'll fix this upstream and update the metadata.
